fix: link error with intel compiler
`~X() = default;` causes link error like `undefined reference to ~X()`
when SEPARATE_BUILD=ON. To avoid it, replace `= default;` by the
equivalent code, `{}` (empty body destructor).